---
- name: Install Bun global tools
  ansible.builtin.command:
    argv:
      - >-
        {{
          prerequisites_homebrew_prefix + '/bin/bun'
          if prerequisites_homebrew_prefix is defined
          else 'bun'
        }}
      - add
      - --global
      - "{{ item.package }}"
  args:
    creates: "{{ dotfiles_home_dir }}/.cache/.bun/bin/{{ item.bin }}"
  environment:
    BUN_INSTALL: "{{ dotfiles_home_dir }}/.cache/.bun"
    PATH: "{{ prerequisites_homebrew_path | default(dotfiles_path) }}"
  loop: "{{ ecosystem_bun_global_packages }}"
  tags:
    - ecosystem
    - bun
