---
- name: Install Bun ecosystem tools
  ansible.builtin.import_tasks: bun.yml
  tags:
    - ecosystem
    - bun

- name: Install Nix ecosystem tools
  ansible.builtin.import_tasks: nix.yml
  when: common_is_linux or common_is_macos
  tags:
    - ecosystem
    - nix
