x-dotfiles-build-args: &dotfiles-build-args
  TEST_USER: dotfiles
  TEST_UID: 1000
  TEST_GID: 1000

x-dotfiles-build: &dotfiles-build
  context: .
  dockerfile: Dockerfile
  pull: true
  target: dotfiles-test
  args: *dotfiles-build-args

x-dotfiles-service: &dotfiles-service
  init: true
  stdin_open: true
  tty: true
  working_dir: /home/dotfiles
  command:
    - ansible-playbook
    - --version

services:
  fedora:
    <<: *dotfiles-service
    image: dotfiles:fedora-test
    build:
      <<: *dotfiles-build
      args:
        <<: *dotfiles-build-args

  fedora-shell:
    <<: *dotfiles-service
    profiles:
      - shell
    image: dotfiles:fedora-test
    build:
      <<: *dotfiles-build
      args:
        <<: *dotfiles-build-args
    working_dir: /workspace/dotfiles
    command:
      - zsh
      - -l
