---
- name: Repair user Flatpak installation
  ansible.builtin.command:
    argv:
      - flatpak
      - repair
      - --user
  changed_when: false
  failed_when: false
  when:
    - host_layer_flatpak_command.rc == 0
    - not ansible_check_mode
  tags:
    - host
    - flatpak
    - flatpak-maintenance

- name: Prune unused user Flatpak references
  ansible.builtin.command:
    argv:
      - flatpak
      - uninstall
      - --user
      - --unused
      - --noninteractive
  changed_when: false
  failed_when: false
  when:
    - host_layer_flatpak_command.rc == 0
    - not ansible_check_mode
  tags:
    - host
    - flatpak
    - flatpak-maintenance

- name: Repair system Flatpak installation
  ansible.builtin.command:
    argv:
      - flatpak
      - repair
      - --system
  become: true
  changed_when: false
  failed_when: false
  when:
    - host_layer_flatpak_command.rc == 0
    - host_layer_system_flatpak.stat.isdir | default(false)
    - not ansible_check_mode
  tags:
    - host
    - flatpak
    - flatpak-maintenance

- name: Prune unused system Flatpak references
  ansible.builtin.command:
    argv:
      - flatpak
      - uninstall
      - --system
      - --unused
      - --noninteractive
  become: true
  changed_when: false
  failed_when: false
  when:
    - host_layer_flatpak_command.rc == 0
    - host_layer_system_flatpak.stat.isdir | default(false)
    - not ansible_check_mode
  tags:
    - host
    - flatpak
    - flatpak-maintenance
