---
- name: Run configured host font scripts
  ansible.builtin.include_tasks:
    file: run-script.yml
    apply:
      tags: "{{ host_layer_script.tags }}"
  loop: "{{ host_layer_font_scripts }}"
  loop_control:
    loop_var: host_layer_script
    label: "{{ host_layer_script.name }}"
  tags:
    - host
    - fonts
    - font-cache
