[nix]
# docker.io/nixos/nix:latest is better for plain podman/docker runs, but it
# lacks the distro metadata and setup tooling Distrobox expects.
image=localhost/nix-distrobox:latest
init=true
nvidia=false
pull=false
replace=false
root=false
start_now=true
volume="/home/linuxbrew:/home/linuxbrew"
