---
- name: Download upstream script commands
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    checksum: "{{ item.checksum | default(omit) }}"
    mode: "0755"
    force: true
  loop: "{{ local_tools_upstream_script_tools | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: common_system in item.platforms
  tags:
    - local
    - scripts
    - upstream
