---
- name: Ensure local bin and cache directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ dotfiles_bin_dir }}"
    - "{{ dotfiles_cache_dir }}"
    - "{{ dotfiles_data_dir }}"
  tags:
    - common

- name: Gather missing operating system facts
  ansible.builtin.setup:
  when: >-
    ansible_facts.get('system', '') == ''
    or ansible_facts.get('architecture', '') == ''
  tags:
    - common

- name: Set operating system facts
  ansible.builtin.set_fact:
    common_system: "{{ ansible_facts.system }}"
    common_architecture: "{{ ansible_facts.architecture }}"
    common_is_macos: "{{ ansible_facts.system == 'Darwin' }}"
    common_is_linux: "{{ ansible_facts.system == 'Linux' }}"
    common_is_nixos: >-
      {{
        ansible_facts.system == 'Linux'
        and ansible_facts.distribution == 'NixOS'
      }}
  tags:
    - common

- name: Detect rpm-ostree
  ansible.builtin.stat:
    path: /usr/bin/rpm-ostree
  register: common_rpm_ostree_binary
  when: common_is_linux
  tags:
    - common

- name: Detect package managers
  ansible.builtin.set_fact:
    common_has_rpm_ostree: >-
      {{
        common_is_linux
        and common_rpm_ostree_binary.stat.executable | default(false)
      }}
  tags:
    - common
