[theme]
dark = "catppuccin_frappe_pink"
light = "catppuccin_latte_pink"
fallback = "catppuccin_frappe_pink"

[editor]
auto-format = true
auto-save = false
idle-timeout = 100
color-modes = true
cursorline = true
line-number = "relative"
true-color = true
kitty-keyboard-protocol = "auto"
mouse = true
bufferline = "always"
completion-replace = true
completion-trigger-len = 1
end-of-line-diagnostics = "hint"
popup-border = "all"
rainbow-brackets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.gutters]
layout = ["diagnostics", "line-numbers", "spacer", "diff"]

[editor.indent-guides]
render = true

[editor.statusline]
center = ["position-percentage"]

[editor.whitespace.characters]
nbsp = "⍽"
newline = "⏎"
space = "·"
tab = "→"
tabpad = "·"
trail = "•"

[editor.lsp]
display-messages = true
display-inlay-hints = true
display-progress-messages = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
git-global = true
git-ignore = true
hidden = false

[editor.soft-wrap]
enable = true

[editor.smart-tab]
enable = true

[editor.search]
smart-case = true
wrap-around = true

[keys.normal]
"{" = "page_cursor_half_up"
"}" = "page_cursor_half_down"
G = "goto_file_end"
g = { g = "goto_file_start", q = ":reflow" }
Z = { Z = ":write-quit", Q = ":quit!" }
"space" = { "space" = "file_picker" }
C-space = "yank_to_clipboard"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
S-tab = "move_parent_node_start"

[keys.select]
"{" = "page_cursor_half_up"
"}" = "page_cursor_half_down"
G = "goto_file_end"
g = { g = "goto_file_start", q = ":reflow" }
Z = { Z = ":write-quit", Q = ":quit!" }
C-space = "yank_to_clipboard"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
