---
prerequisites_homebrew_installer_url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
prerequisites_rustup_installer_url: https://sh.rustup.rs

prerequisites_homebrew_required_commands:
  - btop
  - zellij

prerequisites_bootstrap_packages:
  apt:
    - bubblewrap
    - curl
    - file
    - git
    - podman
    - podman-compose
    - procps
  apk:
    - bubblewrap
    - curl
    - file
    - git
    - podman
    - podman-compose
    - procps-ng
  dnf:
    - bubblewrap
    - curl
    - file
    - git
    - podman
    - podman-compose
    - procps-ng
  pacman:
    - bubblewrap
    - curl
    - file
    - git
    - podman
    - podman-compose
    - procps-ng

prerequisites_build_toolchain_packages:
  apt:
    - binutils
    - build-essential
    - clang
    - cmake
    - libclang-dev
    - libssl-dev
    - lld
    - lldb
    - patch
    - perl
    - pkg-config
    - zlib1g-dev
  apk:
    - binutils
    - build-base
    - clang
    - cmake
    - linux-headers
    - lld
    - lldb
    - openssl-dev
    - patch
    - perl
    - pkgconf
    - zlib-dev
  dnf:
    - binutils
    - clang
    - cmake
    - gcc
    - gcc-c++
    - glibc-devel
    - lld
    - lldb
    - make
    - openssl-devel
    - patch
    - perl
    - pkgconf-pkg-config
    - zlib-devel
  pacman:
    - base-devel
    - binutils
    - clang
    - cmake
    - lld
    - lldb
    - openssl
    - patch
    - perl
    - pkgconf
    - zlib
