---
ecosystem_bun_global_packages:
  - package: "@openai/codex"
    bin: codex
  - package: "@earendil-works/pi-coding-agent"
    bin: pi
  - package: opencode-ai
    bin: opencode

ecosystem_determinate_nix_installer_url: https://install.determinate.systems/nix
ecosystem_nixos_nix_installer_url: https://artifacts.nixos.org/nix-installer
ecosystem_nix_installer_url: >-
  {{
    ecosystem_nixos_nix_installer_url
    if common_is_macos
    else ecosystem_determinate_nix_installer_url
  }}
ecosystem_nix_bin: /nix/var/nix/profiles/default/bin/nix
ecosystem_nix_paths:
  - "{{ ecosystem_nix_bin | dirname }}"
  - /run/current-system/sw/bin
  - "{{ dotfiles_home_dir }}/.nix-profile/bin"
  - "{{ prerequisites_homebrew_path | default(dotfiles_path) }}"
ecosystem_nix_path: "{{ ecosystem_nix_paths | join(':') }}"
ecosystem_eupkgs_flake: github:euvlok/pkgs
ecosystem_nix_profile_packages:
  - package: deadnix
    bin: deadnix
  - package: nh
    bin: nh
  - package: nil
    bin: nil
  - package: nix
    bin: nix-instantiate
  - package: nix-output-monitor
    bin: nom
  - package: nix-tree
    bin: nix-tree
  - package: nixd
    bin: nixd
  - package: nixfmt
    bin: nixfmt
  - package: pi-ssh-tools
    bin: pi-ssh-tools
    source: "{{ ecosystem_eupkgs_flake }}#pi-ssh-tools"
  - package: web-search-pi
    bin: web-search-pi
    source: "{{ ecosystem_eupkgs_flake }}#web-search-pi"
